name = "hourly-dev"
main = "src/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Configuración para desarrollo local sin D1
[vars]
JWT_SECRET = "dev-secret-key-change-in-production"
ENVIRONMENT = "development"
