name = "hourly"
main = "src/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "hourly-prod"

[env.staging]
name = "hourly-staging"

[[d1_databases]]
binding = "DB"
database_name = "hourly-db"
database_id = "f990215e-de16-48e3-ad1a-5a1c9592683e"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[vars]
JWT_SECRET = "hourly-super-secret-jwt-key-production-2024"
ENVIRONMENT = "production"
